name: Call chatgpt

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  chatgpt-interaction:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set up env
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "COMMENTS_URL=${{ secrets.COMMENTS_URL }}" >> $GITHUB_ENV
        echo "POST_ID=${{ secrets.POST_ID }}" >> $GITHUB_ENV
        echo "WP_LELE_USERNAME=${{ secrets.WP_LELE_USERNAME }}" >> $GITHUB_ENV
        echo "WP_LELE_PASSWORD=${{ secrets.WP_LELE_PASSWORD }}" >> $GITHUB_ENV
    - name: Pip install
      run: |
        python --version
        pip install --upgrade openai
        pip install --upgrade requests
    - name: Run gpt_send.py
      run: |
        export COMMENTS_URL=$COMMENTS_URL
        export POST_ID=$POST_ID
        export WP_LELE_USERNAME=$WP_LELE_USERNAME
        export WP_LELE_PASSWORD=$WP_LELE_PASSWORD
        python src/chatgpt/gpt_send.py $OPENAI_API_KEY
